server:
  port: 8005
spring:
  application:
    name: tzwAuth
  # redisson 配置
  redisson:
    # redis key前缀
    keyPrefix:
    # 线程池数量
    threads: 4
    # Netty线程池数量
    nettyThreads: 8
    # 单节点配置
    singleServerConfig:
      # 客户端名称
      clientName: ${spring.application.name}
      # 最小空闲连接数
      connectionMinimumIdleSize: 8
      # 连接池大小
      connectionPoolSize: 32
      # 连接空闲超时，单位：毫秒
      idleConnectionTimeout: 10000
      # 命令等待超时，单位：毫秒
      timeout: 3000
      # 发布和订阅连接池大小
      subscriptionConnectionPoolSize: 50
    # redisson 缓存配置
    cacheGroup:
      # 用例: @Cacheable(cacheNames="groupId", key="#XXX") 方可使用缓存组配置
      - groupId: redissonCacheMap
        # 组过期时间(脚本监控)
        ttl: 60000
        # 组最大空闲时间(脚本监控)
        maxIdleTime: 60000
        # 组最大长度
        maxSize: 0
# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 500
    # 密码锁定时间（默认10分钟）
    lockTime: 10


