eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}-${server.port}
    # 表示 Eureka Client 向 Eureka Server 发送心跳的频率（默认 30 秒），如果在 lease-expiration-duration-in-seconds 指定的时间内未收到心跳，则移除该实例。
    lease-renewal-interval-in-seconds: 30
    # 表示 Eureka Server 在接收到上一个心跳之后等待下一个心跳的秒数（默认 90 秒），若不能在指定时间内收到心跳，则移除此实例，并禁止此实例的流量。
    lease-expiration-duration-in-seconds: 90
  client:
    healthcheck:
      # 允许上报服务状态
      enabled: true
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://tzw:123456@localhost:8002/eureka/
