server:
  port: 8002
spring:
  application:
    name: tzwEureka
  security:
    user:
      name: tzw
      password: 123456

eureka:
  server:
    eviction-interval-timer-in-ms: 5000
    # 关闭缓存
    use-read-only-response-cache: true
    # 关闭自我保护
    enable-self-preservation: true
  instance:
    hostname: localhost
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}-${server.port}-${random.int}
  client:
    prefer-ip-address: true
    register-with-eureka: true #false表示不向注册中心注册自己
    fetch-registry: true #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
