server:
  port: 8004

spring:
  application:
    name: tzwGateWay
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      loadbalancer:
        retry:
          enabled: true
      routes:
        # 路由规则-系统管理
        - id: tzwSystem
          uri: lb://tzwSystem
          predicates: # 断言（判断条件）
            - Path=/tzwSystem/** # 匹配对应的URL请求，将匹配到的请求追加到目标URL后
          filters:
            - StripPrefix=1
        # 路由规则-认证
        - id: tzwAuth
          uri: lb://tzwAuth
          predicates: # 断言（判断条件）
            - Path=/tzwAuth/** # 匹配对应的URL请求，将匹配到的请求追加到目标URL后
          filters:
            - StripPrefix=1
