server:
  port: 8004
spring:
  application:
    name: tzwGateWay
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: tzwConfig
    gateway:
      discovery:
        locator:
          # 是否与服务发现组件进行结合，通过ServiceId转发到具体服务实例
          enabled: true # 是否开启基于服务发现的路由规则
          lower-case-service-id: true # 是否将服务名称转小写
      routes:
        # 路由规则-系统管理
        - id: tzwSystem
          uri: lb://tzwSystem
          predicates: # 断言（判断条件）
            - Path=/** # 匹配对应的URL请求，将匹配到的请求追加到目标URL后
