server:
  port: 8004
spring:
  application:
    name: tzwGateWay
  cloud:
    gateway:
      routes:
        # 系统管理
        - id: my_tzwSystem
          uri: lb://tzwSystem
          predicates:
            - Path=/**
          filters:
            - StripPrefix=1


