server:
  port: 8004
spring:
  application:
    name: tzwGateWay
  cloud:
    gateway:
      routes:
        # 系统管理
        - id: my_tzwSystem
          uri: lb://tzwSystem
          predicates:
            - Path=/**
          filters:
            - StripPrefix=1
            # 降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'
hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #断路器超时时间，默认1000ms

