server:
  port: 8004
spring:
  application:
    name: tzwGateWay
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 系统管理
        - id: tzwModulesSystem
          uri: lb://tzwModulesSystem
          predicates:
            - Path=/sys/**
          filters:
            - StripPrefix=1


