server:
  port: 8004
spring:
  application:
    name: tzwGateWay
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # 系统管理
        - id: my_tzwSystem
          uri: lb://tzwSystem
          predicates:
            - Path=/**
          filters:
            # 意为匹配port后的第一个单词
            - StripPrefix=1

